web:
    image: nginx
    ports:
        - 80:80
    volumes:
        - Laravel:/usr/share/nginx/html
        - Docker/nginx:/etc/nginx/conf.d
    links:
        - php:php

php:
    image: php:5.6.10-fpm
    volumes:
        - Laravel:/usr/share/nginx/html
