web:
    image: nginx
    ports:
        - 80:80
    volumes:
        - Laravel:/usr/share/nginx/html
        - Docker/nginx:/etc/nginx/conf.d
    links:
        - php:php
        - db:db

php:
    build: Docker/php
    volumes:
        - Laravel:/usr/share/nginx/html

db:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
